# ===============================
# SERVIDOR
# ===============================
server.port=8080

# ===============================
# BASE DE DATOS
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/sbe_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SWAGGER
# ===============================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# ===============================
# LOGGING
# ===============================
logging.level.com.sbe.backend=DEBUG
logging.level.org.springframework.web=DEBUG

# JWT
jwt.secret=8fK3mP9xQ2vL7nR4sT6yW1zA5bC8dE0gH3jK7mN9pQ4rS6uV
jwt.expiration-ms=86400000